Added a test for that last slash-normalizing commit.  It fails right now.
The failure is because the node's source_path gains a "filters_site" directory out of nowhere I can discern.

        def test_paths_use_forward_slash():
            config = { }
            path = 'a_folder/page.j2'
            page = JinjaNode(config, get_test_file(path), '')
    >       assert page.source_path == os.path.abspath(path).replace('\\', '/')
    E       assert '/Users/ed/de...older/page.j2' == '/Users/ed/dev...older/page.j2'
    E         Skipping 41 identical leading characters in diff
    E         - ase/tests/a_folder/page.j2
    E         + ase/tests/filters_site/a_folder/page.j2
    E         ?          +++++++++++++